# Обработка исключений try-except

`[Исключение, или ошибка]` - это ситуация, когда выполнение программы прерывается из-за какой-то проблемы или неожиданного условия во время выполнения кода.

`[Ошибка]` - это любое некорректное состояние или действие в программе, которое приводит к нежелательному результату. 
`[Исключение]` - механизм обработки ошибки, который прерывает выполнение программы, при возникновении ошибки. 

- Исключение это специальный объект в Python, который создается в ответ на ошибку во время выполнения программы. Когда возникает ошибка, Python автоматически создает объект-исключение определенного типа и поднимает его (raise), прерывая выполнение кода в текущем контексте.

<details>
  <summary>Категории ошибок</summary>
  
Выделяют три основные категории ошибок:

- Синтаксические
- Логические ошибки
- Время выполнения
#

1. `[Синтаксическая ошибка]` -  это ошибка, возникающая из-за нарушения синтаксиса языка (Неправильное использование ключевых слов, операторов, скобок или отсутствия необходимых элементов, таких как двоеточия, запятые и т. д.).
<details>
  <summary>Основные исключения</summary>

- `SyntaxError`: Это наиболее общее исключение, которое возникает, когда Python не может распознать ваш код из-за ошибки в синтаксисе. Например, забытый двоеточие в конце условия или цикла.
- `IndentationError`: Это возникает, когда отступы в вашем коде не согласованы правильно. Python требует правильного выравнивания для обозначения блоков кода.
- `NameError`: Если вы пытаетесь использовать переменную, которая не была определена, Python вызовет это исключение.
- `TypeError`: Это происходит, когда вы пытаетесь выполнить операцию с объектом несовместимого типа.
- `ZeroDivisionError`: Когда попытка деления на ноль происходит
- `IndentationError`: Ошибка вызвана неправильным форматированием или выравниванием кода.
- `TabError`: Возникает, когда комбинируются табуляция и пробелы для создания отступов в коде.
- `ValueError`: Возникает, когда функция получает аргумент правильного типа, но с недопустимым значением.
</details>

#

2. `[Ошибки времени выполнения]` - возникает, когда программа сталкивается с непредвиденной ситуацией во время выполнения, которая препятствует ее нормальному завершению (некорректные данные, неправильное использование функций или методов, или недоступность ресурсов).
<details>
  <summary>Основные исключения</summary>

1. `OverflowError`: Возникает, когда результат арифметической операции слишком велик для представления.
2. `IndexError`: Возникает, когда индекс последовательности находится вне допустимого диапазона.
3. `KeyError`: Возникает, когда словарь не содержит указанного ключа.
4. `FileNotFoundError`: Возникает, когда пытаемся открыть файл, который не существует.
5. `AttributeError`: Возникает, когда объект не имеет требуемого атрибута.
6. `ImportError`: Возникает, когда не удается импортировать модуль или его атрибут.
7. `MemoryError`: Возникает, когда недостаточно памяти для выполнения операции.
8. `KeyboardInterrupt`: Возникает, когда пользователь прерывает выполнение программы с клавиатуры (например, нажатием Ctrl+C).
9. `StopIteration`: Возникает, когда метод next() итератора вызывается, но итератор исчерпан.
10. `TypeError`: Возникает, когда операция применяется к объекту несовместимого типа.
11. `AssertionError`: Возникает, когда утверждение assert не проходит.
12. `RuntimeError`: Общее исключение для ошибок времени выполнения, которые не вписываются в другие категории.

</details>

#

3. `[Логические ошибки]` - (ошибка проектирования или ошибка алгоритма) - это ошибка в логике программы, которая приводит к некорректным результатам, хотя синтаксически и семантически код может быть правильным. Такие ошибки не вызывают исключений, потому что код технически выполняется без ошибок, но результат его работы не соответствует ожидаемому поведению.

</details>

#

- `[Код возврата]` - (код завершения или код возврата из процесса) - это целочисленное значение, возвращаемое программой при ее завершении. Этот код представляет собой способ сообщить вызывающему процессу или системе операций об успешном или неуспешном завершении программы и может содержать информацию о том, были ли выполнены какие-либо операции успешно или нет

<details>
  <summary>Пример</summary>

Метод `find()` используется для поиска подстроки в строке и возвращает индекс первого вхождения этой подстроки в строке. Если подстрока не найдена, метод возвращает -1. 
```
sentence = "Пример строки для поиска"
substring1 = "уют"
substring2 = 'строки'

index1 = sentence.find(substring1)
index2 = sentence.find(substring2)
print(index1) # -1
print(index2) # 7 
```
</details>





























#
<details>
  <summary></summary>


</details>
